# Generated by Django 5.2.8 on 2025-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del animal.', max_length=100)),
                ('especie', models.CharField(help_text='Perro o Gato.', max_length=50)),
                ('raza', models.CharField(help_text='Raza del animal (puede ser compuesta/mestizo).', max_length=150)),
                ('sexo', models.CharField(help_text='Macho o Hembra.', max_length=10)),
                ('edad_años', models.IntegerField(help_text='Edad del animal en años.')),
                ('peso', models.DecimalField(decimal_places=1, help_text='Peso en kg.', max_digits=4)),
                ('tamaño', models.CharField(help_text='Pequeño, Mediano, Grande, Gigante.', max_length=50)),
                ('color_pelaje', models.CharField(help_text='Descripción del color y tipo de pelo.', max_length=150)),
                ('apto_con', models.TextField(help_text='Lista de requisitos obligatorios del hogar (separados por coma).')),
                ('condicion_especial', models.CharField(help_text='Nombre de la condición médica o conductual, si aplica.', max_length=255)),
                ('desparasitado', models.BooleanField(default=False, help_text='¿Está desparasitado?')),
                ('esterilizado', models.BooleanField(default=False, help_text='¿Está esterilizado?')),
                ('con_microchip', models.BooleanField(default=False, help_text='¿Tiene microchip?')),
                ('vacunado', models.BooleanField(default=False, help_text='¿Está vacunado?')),
                ('adoptado', models.BooleanField(default=False, help_text='True si ya fue adoptado.')),
                ('caracter_necesidad', models.TextField(help_text='Palabras clave de carácter y necesidades (separadas por coma).')),
                ('historia_breve', models.TextField(help_text='Historia de rescate o procedencia.')),
                ('biografia_final', models.TextField(help_text='Biografía emocional generada (Manual o por IA).')),
                ('foto', models.ImageField(blank=True, help_text='Foto principal del animal.', null=True, upload_to='animal_pics/')),
            ],
            options={
                'verbose_name_plural': 'Animales',
                'ordering': ['nombre'],
            },
        ),
    ]
